-- You are given two strings s and t.

-- String t is generated by random shuffling string s and then add one more letter at a random position.

-- Return the letter that was added to t.

module FindTheDifference
  (
    findTheDifference
  ) where

import Data.Char ( ord
                 , chr )
import Data.Bits ( Bits(..) )

findTheDifference :: String -> String -> Char
findTheDifference a b = foldr1 xor $ a <> b

instance Bits Char where
  a .&. b = chr $ ord a .&. ord b
  a .|. b = chr $ ord a .|. ord b
  a `xor` b = chr $ ord a `xor` ord b
  complement a = chr . complement $ ord a 
  a `shift` n = chr $ ord a `shift` n
  a `rotate` n = chr $ ord a `rotate` n
  bitSize a = maybe undefined id . bitSizeMaybe $ ord a 
  bitSizeMaybe a = bitSizeMaybe $ ord a
  isSigned a = isSigned $ ord a
  a `testBit` n = ord a `testBit` n
  bit n = chr $ bit n
  popCount a = popCount $ ord a
